name: Markdown Lint

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: '**/*.md'
          config: |
            {
              "default": true,
              "MD013": false,
              "MD033": false,
              "MD041": false
            }